### PR TITLE
nvme-print-stdout: add nvm-id-ctrl command VER and LBAMQF fields

### PR DESCRIPTION
**Pull request by ikegami-t**
The fields added by NVM command set specification 1.1.

### CODE REVIEW

**Comment by ikegami-t** [comment]
The changes depended on the libnvme PR https://github.com/linux-nvme/libnvme/pull/916.

**Comment by igaw** [comment]
just added the libnvme wrap update and rebased it.

**Comment by igaw** [comment]
Thanks!

**Comment by ikegami-t** [comment]
Thank you.

**Pull request merged**
