### PR TITLE
json.c - fix crash with empty strings, fix escape for special chars.

### PR DESCRIPTION
**Pull request by bdeyal**
Fix program crashed when strdup escape got "" as input.
Fix json generation  - covers more characters that needed escape

### CODE REVIEW

**Comment by keithbusch** [comment]
what path is leading to print strings with non-printable characters?

**Comment by bdeyal** [comment]
Added for completeness. This may be useful for cases where controllers (e.g. in development) return junk when ascii characters are expected. I still  want to print JSON correctly.

**Comment by keithbusch** [comment]
we should just bail if any character fails 'isprint'. We don't aim to support non-compliant drives.

**Comment by bdeyal** [comment]
So other than '\"' and '\\' nothing should be escaped, that means old code is OK except for segfault in case of empty string "" field

**Comment by bdeyal** [comment]
Note:
In the examples below, /dev/nvme0 is a discovery controller (on an io controller everything's fine)
```
# nvme-upstream version
nvme version 1.6.19.ge3da

# nvme-upstream id-ctrl /dev/nvme0 -o json
Allocation of memory for json object failed, aborting.
Aborted (core dumped)

# nvme-fix_json version
nvme version 1.6.14.g6c31

# nvme-fix_json id-ctrl /dev/nvme0 -o json
(Prints empty strings in json OK)
```

**Comment by bdeyal** [comment]
Please comment if no merge, 
I will close iif so.
Thanks.

**Comment by bdeyal** [comment]
If id-ctrl JSON output for a discovery controller is not important then just leave it as it is now.

**Pull request closed without merging**
