### PR TITLE
list-subsys: show PCIe device addresses of local devices, even when running on legacy kernels

### PR DESCRIPTION
**Pull request by freezer5**
See issue https://github.com/linux-nvme/nvme-cli/issues/388

### CODE REVIEW

**Comment by keithbusch** [comment]
Hm, I'm not sure if this provides us much more than what "list-subsys" provides.

**Comment by freezer5** [comment]
list-subsys works with kernel 4.15, some people still use older versions...

**Comment by keithbusch** [comment]
Oh, you're right. Will take another look then.

**Comment by freezer5** [comment]
Reworked code so that list-subsys will still be able to get the PCIe address on older kernels.

**Pull request merged**
