### PR TITLE
nvme: Allow standard SI units for ns-create nsze and ncap input

### PR DESCRIPTION
**Pull request by ikegami-t**
This is proposed by the issue #1747.

Signed-off-by: Tokunori Ikegami <ikegami.t@gmail.com>

### CODE REVIEW

**Comment by keithbusch** [comment]
I feel like we need entirely new arguments, and ensure they're mutually exclusive with the existing nsze/ncap args. The old ones follow the spec defined units, so I think it'd actually be more confusing to repurpose them to include si units.

**Comment by ikegami-t** [comment]
Okay I will do split as new arguments. Thank you.

**Review by igaw — CHANGES_REQUESTED** [review]
- Merge the 3 patch into 1.
- Provide documentation for these new arguments.
- Please add commit message text not just referencing the github issues.. Commit messages should be self-explanatory. This also avoids strong dependency on infrastructure we don't control.

Thanks!

**Comment by ikegami-t** [comment]
Updated the commit as mentioned.

**Review by igaw — APPROVED** [review]

**Comment by igaw** [comment]
Looks good! Thanks!

**Pull request merged**
