### PR TITLE
Fix the bug of Model Number and display the info of Serial Number

### PR DESCRIPTION
**Pull request by seehearfeel**
According to the NVMe Specification, there is an error when display Model Number.
In addition, currently it does not display the info of Serial Number, so add it.

### CODE REVIEW

**Comment by keithbusch** [comment]
Oh no, why did we write it with hard-coded lengths instead of a `printf("%.*s\n", (int)sizeof(field), field)` Thanks for the catch.

I don't know if we want to include the serial number in the list output, though. That output is already too long for most terminal displays. We should be reducing the information it prints since it's unnecessarily duplicated across multi-namespace devices.

**Comment by seehearfeel** [comment]
Thanks for your reply.

In my opinion, it is a fixed value of (int)sizeof(field) due to (int)sizeof(list_item.ctrl.mn) is always 40, because there is a member declaration:
char            mn[40];
in the struct nvme_id_ctrl at the line 66 of linux/nvme.h file.

Generally, the Serial Number is a basic and important info for a disk like Model Number and Firmware Revision. So I think there is no need to use (int)sizeof(field) and display the Serial Number is necessary.

**Comment by keithbusch** [comment]
Right, understood. I just didn't want to have to write "40" for each time we want to print it (or "20" for mn, and "8" for fr, for that matter). We already wrote the size into the structure, so why not let the print format specifier figure out the length on it's own? The linux kernel prints these fields in sysfs that way.

**Comment by seehearfeel** [comment]
OK, I see, thanks for your suggestion.

I have modified the related code of Serial Number, Model Number and Firmware Revision,
other fields are not be changed because the length can not be properly figured out by
the print format specifier, (int)sizeof(field) is too big and (int)strlen(field) is random.
In addition, fix a minor spelling mistake "Namepace" to "Namespace".

Please review, thanks!

**Pull request merged**
