### PR TITLE
intel: enable intel-nvme.c build without json-c dependencies checking

### PR DESCRIPTION
**Pull request by ikegami-t**
Only build json print codes with CONFIG_JSONC build option instead.

### CODE REVIEW

**Comment by igaw** [comment]
Thanks!

**Comment by HaroPanosyan** [comment]
Intel sold it's SSD business 3 years ago to SK Hynix and they started a new company called Solidigm which I work for. We have Solidigm plugin and our plan is to eventually deprecate Intel plugin. We are thinking of having warning message so anyone using Intel plugin to consider start using Solidigm plugin.
Any help/suggestion how we can properly do this would be very nice. Thanks.

**Comment by ikegami-t** [comment]
At first seems better create an issue also for the @HaroPanosyan mention since the PR already merged. Sorry I am not sure about that but seems good to delete the plugin on newer version nvme-cli and then mentioed it by the release note cleary. (By the way for example the toshiba plugin looks as long time not maintained. Also Toshiba SSD business separated from Toshiba to Toshiba memory before then now change the company name also to Kioxia. So seems the plugin also can be deleted.)

**Comment by HaroPanosyan** [comment]
Thanks. There could be still some users, so I was thinking instead of deleting, allow some time by just showing "soon to be deprecated, instead use Solidigm plugin" message or something like that.

**Comment by ikegami-t** [comment]
Okay I see. By the way the intel plugin is older but the newer version solidigm plugin will support the same command feature. Is this really correct? Or is the command specification basically same for the old features on both intel and solidgm SSDs?

**Comment by HaroPanosyan** [comment]
Correct, we already should cover everything intel plugin does and more. We have newer drives with newer Vendor Unique (VU) logs/features and we plan Solidigm plugin to be where everything goes and eventually deprecate/delete Intel plugin.

**Comment by ikegami-t** [comment]
Noted. Thank you.

**Pull request merged**
