### PR TITLE
nvme: fix formatNVM command

### PR DESCRIPTION
**Pull request by ganaidu707**
Remove unassigned variable "lbads" and change metadata
settings config parameter from "ms" to "mset" (as per
NVM Express)."ms" is reference for metadata size in general.

Signed-off-by: Gollu Appalanaidu <anaidu.gollu@samsung.com>

### CODE REVIEW

**Comment by minwooim** [comment]
I'm afraid that it might be late to update the parameter name of format command.

Format NVM commands are widely being taken to format namespaces in various systems already.  `--ms` might be confusing, of course, because there is Metadata Size(MS) field in LBA Format data structure, but I am not sure this is a good time to change this param name.

**Comment by ganaidu707** [comment]
Thanks @minwooim for the comment, understand the concern.
Lets take Keith's opinion and decide on this.

**Comment by ganaidu707** [comment]
closing this PR, as @minwooim mentioned its very late to change to the parameter.

**Comment by MatiasBjorling** [comment]
The shorthand has historically been (MS) in the specification. Given that it is used by many scripts, it would cause a lot of grief to update to the MSET shorthand in the later revisions.

**Comment by keithbusch** [comment]
Any change in parameter names at this point will need to work out how to create alias's to the previous name.

**Pull request closed without merging**
