### PR TITLE
nvme: Return negative error value

### PR DESCRIPTION
**Pull request by minwooim**
Hi @keithbusch ,

IMHO, It would be nicer if we have a ruled return types for
subcommands like the following:
  - subcommand plugin handler returns
    - positive: nvme status
    - negative: internal errno value
    - 0: success

```
Some subcommands does not currently returning negative value, but some
do.  It needs to be consistant that when it returns a positive value, it
can mean the nvme status, if it's negative, then it can mean an internal
error has occurred.

Signed-off-by: Minwoo Im <minwoo.im.dev@gmail.com>
```

### CODE REVIEW

**Comment by keithbusch** [comment]
For the exit status? That's an unsigned byte, and should be the errno value by convention. Making it negative will have `echo $?` report the wrong status.

**Comment by minwooim** [comment]
@keithbusch ,

You're right. if we go through `echo $?` then it will show -err value like 254
or some reduced value from 255.

Then, how do you think about changing all the return values to a positive
values because we always print the nvme status error if it occurs which
means we don't need to pass the nvme status code to the actual main().

What do you say?

**Comment by minwooim** [comment]
I mean there are few cases that return negative value with errr value.
I think it needs to be uniformized.

**Comment by keithbusch** [comment]
Oh, good point. I think we should return 0 if we got a valid response, not the nvme status.

**Comment by minwooim** [comment]
Alright, then I'll prepare V2 patchsets with zero-returning in case
nvme completion has been successfully done.

**Comment by minwooim** [comment]
@keithbusch ,

I have one doubt here.  How do you think a program will recognize that the
given subcommand succeeded or not in case nvme cqe has been received well.

If we are going to return 0 for both success case and nvme error cases,
the only thing we know is the print-out messages of nvme status.  But there
are only few "success" prints, most of them do not print out "success".

I think a program would like to invoke a subcommand and want to know the
status of it.

Do you want it to be done by parsing the print-out messages only ? not by
the return value of this program.

Thanks ;)

**Comment by keithbusch** [comment]
Since we only have 8 bits for exit status, and nvme status are 16 bits, status collisions are possible, so you won't be able to tell what the status means.

The way I look at it, a 0 status code would mean the program was able to send the requested command and receive a reply. A non-zero status means some other error happened preventing a transaction with the device. from occuring

**Comment by minwooim** [comment]
Hah, my bad ;)
Even I told you 255 which is 8 bits, I was thinking it could handle nvme error
status which is 16 bits. 
Let me prepare V2 patcheset for this one. 

Thanks!

**Comment by minwooim** [comment]
PR #492 has been raised for V2. so closed.

**Pull request closed without merging**
