### PR TITLE
nvme-cli: fix endianess in WDC plugin.

### PR DESCRIPTION
**Pull request by tim-oleksii**
Signed-off-by: Oleksii Timofieiev <tim.oleksii@gmail.com>

### CODE REVIEW

**Comment by tim-oleksii** [comment]
@jeffreyalien Could you please review?

**Comment by jeffreyalien** [comment]
I have review the changes and they look fine.  I plan to verify the changes too, but will probably need to get some special firmware code to set those stats to something other then 0's.  That might take a few days or so.   I'll comment as soon as I get it verified.

**Comment by keithbusch** [comment]
Thanks, Jeff. I think this looks correct too just based on how it looked before, so I'll pull in now and we can make additional fixes if you find them.

**Comment by tim-oleksii** [comment]
Thank you!

**Comment by jeffreyalien** [comment]
I was able to verify the changes with non-zero data and all looks good.   No additional changes will be needed.

**Pull request merged**
