### PR TITLE
fdp: bug fix for data size of fdp status

### PR DESCRIPTION
**Pull request by sc108-lee**

### CODE REVIEW

**Comment by igaw** [comment]
Please provide a better commit message. 'Bug fix' is a bit terse.

@birkelund Any objections?

**Comment by birkelund** [comment]
> @birkelund Any objections?

LGTM!

**Comment by sc108-lee** [comment]
@igaw rebased and modified.
I thought data size looks obviously wrong.
But if someone doesn't know the spec, might confuse
So added more details on message as you recommended

fdp: Fix wrong Reclaim Unit Handle Status size

size should include reserved, NRUHSD bytes
that exist before Reclaim Unit Handle Status Descriptor List

**Comment by igaw** [comment]
Thanks. Well it might be obvious when reading all the code around. Just by looking at the commit I can't decide.

**Pull request merged**
