### PR TITLE
Add WDC plugin clear-fw-activate-history command 

### PR DESCRIPTION
**Pull request by jeffreyalien**

### CODE REVIEW

**Comment by keithbusch** [comment]
is it possible to squash this down so we don't have the merges, reverts, and the revert reverts?

**Comment by jeffreyalien** [comment]
Yea, I’ll if I can get them squashed down and resubmit the pull request.  Sorry for the mess.


Jeff Lien

**Comment by keithbusch** [comment]
Is this still valid? I'm not quite sure how to handle this, we just want to see a single commit in the pull requets, but there's still merge commits as well.

**Comment by jeffreyalien** [comment]
No, it's not valid or needed anymore.   Is there away for me to delete or withdraw this request?  I didn't see a way from the git gui.  Is there a command to do it?  Or did I just miss it in the gui?

**Pull request closed without merging**
