### PR TITLE
nvme: change to use libnvme cleanup functions

### PR DESCRIPTION
**Pull request by ikegami-t**
Delete duplicated functions and change _cleanup_file_ to _cleanup_fd_.

### CODE REVIEW

**Comment by ikegami-t** [comment]
Depended on the linux-nvme/libnvme#858.

**Comment by igaw** [comment]
I don't want to export the private `cleanup.h` file from libnvme. We can update version in nvme-cli using the same names as in libnvme though.

**Comment by ikegami-t** [comment]
Just updated the nvme-cli version to use the same names as in libnvme.

**Comment by igaw** [comment]
Thanks!

**Pull request merged**
