### PR TITLE
nvme-print-json: Fix compilation fails if json-c is not enabled

### PR DESCRIPTION
**Pull request by ikegami-t**

### CODE REVIEW

**Comment by ikegami-t** [comment]
Fix for the issue #1947.

**Comment by yhr** [comment]
Compilation finishes, but linking fails when I'm building:

```
[93/93] Linking target nvme
FAILED: nvme 
cc  -o nvme nvme.p/nbft.c.o nvme.p/fabrics.c.o nvme.p/nvme.c.o nvme.p/nvme-models.c.o nvme.p/nvme-print.c.o nvme.p/nvme-rpmb.c.o nvme.p/nvme-wrap.c.o nvme.p/plugin.c.o nvme.p/libnvme-wrap.c.o nvme.p/ccan_ccan_list_list.c.o nvme.p/ccan_ccan_str_debug.c.o nvme.p/ccan_ccan_str_str.c.o nvme.p/util_argconfig.c.o nvme.p/util_base64.c.o nvme.p/util_cleanup.c.o nvme.p/util_crc32.c.o nvme.p/util_suffix.c.o nvme.p/util_types.c.o -Wl,--as-needed -Wl,--no-undefined '-Wl,-rpath,$ORIGIN/subprojects/libnvme/src' -Wl,-rpath-link,/home/hans/repos/nvme-cli/.build/subprojects/libnvme/src -Wl,--start-group subprojects/libnvme/src/libnvme.so.1.4.0 subprojects/libnvme/src/libnvme-mi.so.1.4.0 -ldl -Wl,--end-group
/usr/bin/ld: nvme.p/nbft.c.o: in function `json_connect_msg':
/home/hans/repos/nvme-cli/.build/../nbft.c:23: undefined reference to `json_create_object'
/usr/bin/ld: /home/hans/repos/nvme-cli/.build/../nbft.c:24: undefined reference to `json_object_add_value_string'
/usr/bin/ld: /home/hans/repos/nvme-cli/.build/../nbft.c:26: undefined reference to `json_print_object'
/usr/bin/ld: /home/hans/repos/nvme-cli/.build/../nbft.c:28: undefined reference to `json_free_object'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

```

**Comment by igaw** [comment]
This looks like we should add a CI build for this configuration. Though I think it would be better to write a shell script for all the build configurations and just call the script from the yaml file. This would make the CI build more independent from the github workflow, e.g. running these locally. I saw this trick in the D-Bus project.

**Comment by igaw** [comment]
Thanks @ikegami-t , I've merged my fixes as there were a few more nessary when json-c is not available. The CI muon-minimal build is configured to build without json-c, thus we will catch these issue when a PR is submitted in future.

**Comment by ikegami-t** [comment]
Thank you so much.

**Pull request closed without merging**
