### PR TITLE
nvme-cli: Add script to determine host NQN

### PR DESCRIPTION
**Pull request by hreinecke**
Add a script to create a deterministic hostnqn which remains stable across reinstalls.
* Based on the system-UUID via dmidecode
* verifies UUID format
* tries to catch fake/lazy UUIDs

### CODE REVIEW

**Comment by simson-suse** [comment]
As a side note: I originally named the script `det-hostnqn`, to distinguish it from the already existing `nvme-cli gen-hostnqn`, which creates a random hostnqn. But I don't have a strong opinion on this.

**Comment by hreinecke** [comment]
I know. But 'nvme-det-hostnqn' is not very clear about what it's doing. 'nvme-gen-hostnqn' is more in-line with existing naming schemes. But yes, there is the confusion between 'nvme-gen-hostnqn' and 'nvme gen-hostnqn'.
Let Keith decide :-)

**Comment by keithbusch** [comment]
I like it! Maybe the existing gen-hostnqn should attempt to get system uuid before falling back to random uuid.

**Comment by keithbusch** [comment]
Yeah, I think I'll try system's uuid first instead of random with the tool's gen-hostnqn command. I initially didn't want to decode /sys/firmware/ tables, but it looks like someone already puts the result in a convenient place: /sys/devices/virtual/dmi/id/product_uuid.

**Pull request merged**
