### PR TITLE
ocp: OCP 2.5 Telemetry DA 1 and 2 Parsing Updates

### PR DESCRIPTION
**Pull request by jeff-lien-wdc**
This commit will provide the first phase of changes needed for parsing of OCP 2.5 Telemetry Log Pages 7h and 8h, Data Areas 1 and 2.  It will decode the predefined classes for Data Area 1 and 2 Statistics, and Event FIFO's.

### CODE REVIEW

**Comment by jeff-lien-wdc** [comment]
@igaw I did add 2 new files in this PR (ocp-telemetry-decode.c and h) and now getting this checkpatch failure:
WARNING: added, moved or deleted file(s), does MAINTAINERS need updating?

How do I fix it?

**Comment by igaw** [comment]
You can ignore this specific failure.  We don't have a MAINTAINERS file (yet). Maybe we could add one and make github smart to add the reviewers to the PRs... just joking.

**Comment by igaw** [comment]
@arthurshau please have a look.

**Comment by jeff-lien-wdc** [comment]
> You can ignore this specific failure. We don't have a MAINTAINERS file (yet). Maybe we could add one and make github smart to add the reviewers to the PRs... just joking.

Ok, thanks for clarifying.  I looked for a MAINTAINERS file but couldn't find one.  I see I still have a few build failures to still fix.  I'll fix them up now.

**Comment by igaw** [comment]
checkpatch is from the Linux kernel, thus it expects the layout etc from the Linux project. Not all makes sense in our context. I consider checkpatch a helper to make my reviews simpler, but it has also drawbacks as sometimes has some very stupid ideas how some code should look like. So it's good  advice to use some sense when to follow the warnings/errors and when not.

**Comment by arthurshau** [comment]
LGTM!

**Comment by igaw** [comment]
Thanks! 

So if I get this right, this supersedes https://github.com/linux-nvme/nvme-cli/pull/2374 correct?

**Comment by VigneshwaranSaravana** [comment]
https://github.com/linux-nvme/nvme-cli/pull/2374 implementation merged with this PR

**Comment by VigneshwaranSaravana** [comment]
@igaw - We have observed some issue in this PR merged code (like NUMD not in divisible by 512 and segmentation issue while printing statistic info). We are planning to fix this issue.

**Comment by jeff-lien-wdc** [comment]
@VigneshwaranSaravana Please include me as a reviewer in your PR.  Thanks.

**Pull request merged**
