### PR TITLE
MAINT: Fix clang-format indentation errors

### PR DESCRIPTION
**Pull request by ikegami-t**
Corrected by the clang-format tool with the linux kernel style.
Also .clang-format file used by linux kernel as the following page.
  https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/.clang-format

Note: The tool is executed as below command.
  find . -iname -iname "*.c" | xargs clang-format -i

Signed-off-by: Tokunori Ikegami <ikegami.t@gmail.com>

### CODE REVIEW

**Comment by ikegami-t** [comment]
To make sure could you please let me confirm this coding style fix PR again?
In this PR .clang-format opiton file is changed from the llvm clang-format example to the actual linux kernel option file.
It seems that it is improved but is this result still bad?

**Review by hreinecke — APPROVED** [review]
Looks okay.

**Comment by hreinecke** [comment]
But can you please rebase to the latest HEAD?

**Comment by ikegami-t** [comment]
Thansk for the review. Just rebased the changes.

**Comment by ikegami-t** [comment]
Sorry fixed the commit message error by the last commit force-pushed.

**Comment by igaw** [comment]
@hreinecke do you really want this clang reformatting thing in? Obviously, it would make all the code base consistent but with all the problems that come along with it.

**Comment by igaw** [comment]
FWIW, While I like the idea of having a format checker, I don't like the result of this mechanical transformation. @hreinecke still in favor this approach?

**Comment by igaw** [comment]
Okay, as no one is really for this change, I am closing this one.

**Pull request closed without merging**
