### PR TITLE
MAINT: Fix clang-format indentation errors

### PR DESCRIPTION
**Pull request by ikegami-t**
Corrected by the clang-format tool with the linux kernel style.
Also .clang-format file desribed by the following page.
  https://clang.llvm.org/docs/ClangFormatStyleOptions.html#examples

Note: The tool executed as below command.
  find . -iname "*.h" -o -iname "*.c" | xargs clang-format -i

Signed-off-by: Tokunori Ikegami <ikegami.t@gmail.com>

### CODE REVIEW

**Comment by ikegami-t** [comment]
Now trying to fix the build errors by the libnvme pull request change #140.

**Comment by igaw** [comment]
The final result is certainly consistent but it uglifies a lot of code, IMO. Also it ruins 'git blame' considerable.

@hreinecke do you think we should do a massive whitespace cleanup like this?

**Comment by ikegami-t** [comment]
> The final result is certainly consistent but it uglifies a lot of code, IMO. Also it ruins 'git blame' considerable.
> 
> @hreinecke do you think we should do a massive whitespace cleanup like this?

Thanks for your comment. Let me reply to you as below.
1. It looks the issue can be resolved by the git blame -w option below.
```
-w
Ignore whitespace when comparing the parent’s version and the child’s to find where the lines came from.
```
2. The .clang-format used in the linux kernel seems better to reuse than the clang format style example in the PR.
  <https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/.clang-format>
3. Seems better to be checked by the CI build to prevnet the coding sytle erorr after the format at first.

By the way the CI builds error can be resovled by adding the option below into the .clang-format file.
```
SortIncludes:false 
```

**Comment by igaw** [comment]
While the 'git blame -w' might work (haven't tried it out) you completely ignored my first argument. The resulting code looks pretty bad. I am fine with having coding style fixes but not in this way. Sorry.

**Pull request closed without merging**
