### PR TITLE
nvme-cli: Add friendly status messages

### PR DESCRIPTION
**Pull request by rrosatti**
Additional messages were added on nvme_status_to_string(), in
order to make the returned status easier to understand.
The messages were based in the Description of those statuses in
the NVMe Specification (v1.3), from the figures 31-36.

Signed-off-by: Rodrigo R. Galvao <rosattig@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by rrosatti** [comment]
Keith, instead of removing the stringified name of the #define's, I used it and added the newly "friedly error messageges" to them. Here are some examples I could get:

1. Trying to create a new namespace, after reach the maximum number possible:

[root@ltc-zz4-lp13 nvme-cli]# ./nvme create-ns /dev/nvme0 -s 1000000 -c 1000000 -f 0 -d 0 -m 0
NVMe Status:NS_ID_UNAVAILABLE: The number of namespaces supported has been exceeded(116)


2. Trying to attach a invalid namespace number

[root@ltc-zz4-lp13 nvme-cli]# ./nvme attach-ns /dev/nvme0 -n 5 -c 0x1
NVMe Status:INVALID_NS: The namespace or the format of that namespace is invalid(200b)


3. Trying to get log information from an invalid page identifier:

[root@ltc-zz4-lp13 nvme-cli]# ./nvme get-log /dev/nvme0 -l 1 -i 10
NVMe Status:INVALID_LOG_PAGE: The log page indicated is invalid. This error condition is also returned if a reserved log page is requested(2109)


If you want me to change something or make new tests, just let me know!

**Comment by keithbusch** [comment]
I'm totally fine with the output results here. Thanks for doing that.

The patch, though, has a bit of whitespace damage. Is your editor set to expand tabs to spaces? The generic sources of this project use the Linux kernel coding style, which uses tabs. Could you fix that up real quick and I'll merge it?

**Comment by rrosatti** [comment]
No problem!

Oh I see .. my VIM config. just messed all the namespaces. I think I can fix that up tonight or tomorrow morning. Sounds good?

**Comment by keithbusch** [comment]
No problem, whenever you have a chance.

**Comment by rrosatti** [comment]
Keith, I did a patch to fix the whitespace mess. But, it seems it's still not right. This is the commit in my nvme-cli forked repo: https://github.com/rrosatti/nvme-cli/commit/2900430e948295901852f0e2ce80ed9e25258656

Could you check if it's correct, please?

**Comment by keithbusch** [comment]
Yah, it's still off. You're using VIM you say? Try aligning after ":set tabstop=8".

**Comment by rrosatti** [comment]
Keith, I believe I got it now. Can you check it, please?

**Comment by keithbusch** [comment]
Yes!! That looks good.

**Comment by rrosatti** [comment]
Thanks!!

**Pull request merged**
