### PR TITLE
Fixed option checking for format to match NVMe spec limits.

### PR DESCRIPTION
**Pull request by braschul**
I noticed the format command help text text was a little off from the spec and the range checking was also not respecting the spec defined values.  Updated the help text and option range checking.  Please let me know if these changes are out of line.

### CODE REVIEW

**Comment by braschul** [comment]
Ok - that's fair.  Mind if I put a comment in those checks to say as much?  Any comments on my help-text changes?

**Comment by keithbusch** [comment]
The help text update looks good to me. Also okay on proposed code comments.

**Comment by braschul** [comment]
Ok - should be good now?

**Comment by keithbusch** [comment]
Looks fine to me. I'll pull the series. Normally we'd ask this to be a single commit to keep the logs clean, but I don't have the moral backing to do so based on my own commit history. :)

**Pull request merged**
