### PR TITLE
Add Dera plugin extension.

### PR DESCRIPTION
**Pull request by Dequan-Dera**
Add stat sub-command to retrieve Dera device status and additional SMART log.

### CODE REVIEW

**Comment by keithbusch** [comment]
Please provide a man page (just the .txt format) for your dera- commands in Documentation/.

**Comment by Dequan-Dera** [comment]
Thanks. I just added the man page txt file.

**Comment by asavah** [comment]
This was merged without even compiling.
```
plugins/dera/dera-nvme.c: In function ‘get_status’:
plugins/dera/dera-nvme.c:129:7: error: too many arguments to function ‘parse_and_open’
  129 |  fd = parse_and_open(argc, argv, desc, command_line_options, NULL, 0);
      |       ^~~~~~~~~~~~~~
In file included from plugins/dera/dera-nvme.c:12:
./nvme.h:84:5: note: declared here
   84 | int parse_and_open(int argc, char **argv, const char *desc,
      |     ^~~~~~~~~~~~~~
make[2]: *** [Makefile:84: plugins/dera/dera-nvme.o] Error 1
```
The fix is trivial but ...
Good job both the submitter and the maintainer. ))

**Comment by keithbusch** [comment]
Eh, that sucks. Shouldn't do pulls from my phone...

**Comment by keithbusch** [comment]
Reverted

**Pull request merged**
