### PR TITLE
plugins/micron: Move OCP internal log parsing from Micron to OCP Plugin.

### PR DESCRIPTION
**Pull request by saskchaithanya**
**Description:**

- Move OCP internal log parsing from Micron to OCP Plugin.
- Datacenter NVMe SSD Specification v2.5r9 section 4.9. 
- Previous PR: https://github.com/linux-nvme/nvme-cli/pull/2354

**CLI Examples:**
[Testing.txt](https://github.com/user-attachments/files/16228248/Testing.txt)

### CODE REVIEW

**Comment by igaw** [comment]
@arthurshau could have a look at this PR? Thank!

**Comment by arthurshau** [comment]
Yeah, looks reasonable to me

**Comment by igaw** [comment]
Thanks!

**Comment by saskchaithanya** [comment]
Thanks @igaw and @arthurshau!

**Pull request merged**
