### PR TITLE
Splitting responsibilities

### PR DESCRIPTION
**Pull request by keithbusch**
This looks like a large change, but it's really just moving where things are defined. This splits the ioctl submission and structure printing into their own files and should make it easier to maintain as separate entities.

There shouldn't be any functional change here, but sending a pull request for potential second opinions.

Last patch just cleans up whitespace damage and irking formatting issues. Maybe we should have a reference to a preferred coding style. I initially adopted the linux kernel's, but we don't necessarily have to do that.

### CODE REVIEW

**Comment by sbates130272** [comment]
Looks good. I am keen to stick to kernel coding style though I am not sure the libs we use for the command line parsing conform to that. For the nvme-* files though we can push for that style.

**Comment by keithbusch** [comment]
Speaking of the parsing component, I have a patch that makes it much simpler to define long and short options together. Right now it's only for the nvme version of this. Would you prefer these go to the original arg-parse project instead of continuing the nvme specifics we currently have?

**Comment by sbates130272** [comment]
Keith - Feel free to just change it in nvme-cli. The master repo for this is diverged quite a bit at this point.

**Comment by keithbusch** [comment]
In that case, any qualms if I change the indent style to match?

**Comment by sbates130272** [comment]
No. Please do ;-).

**Comment by keithbusch** [comment]
Closing request, applied directly.

**Pull request closed without merging**
