### PR TITLE
connect-all: fix exit code on fail to write to /dev/nvme-fabrics

### PR DESCRIPTION
**Pull request by bdeyal**
Scenario:
1. A nvme controller already exists for FC traddr and host_traddr
2. Running connect all with those parameters again failed
3. nvme-cli result is:
   "Failed to write to /dev/nvme-fabrics: Operation already in progress"
4. Exit code for nvme cli is 0
5. After the fix of this commit, exit code is EALREADY (114)

More info:
```
# nvme connect-all \
--host-traddr=nn-0x20000090fa94845f:pn-0x10000090fa94845f \
--hostid=d8266f50-5f24-4c55-8959-23d500e4e450 \
--hostnqn=nqn.2014-08.org.nvmexpress:uuid:d8266f50-5f24-4c55-8959-23d500e4e450 \
--traddr=nn-0x500507680c00002b:pn-0x500507680c2a002b \
--transport=fc
Failed to write to /dev/nvme-fabrics: Operation already in progress

# echo $?
0
```

From strace we can see that discovery controller and discovery log page commands
were ok but the creation of the nvme (io) controller failed with EALREADY
```
open("/dev/nvme-fabrics", O_RDWR)       = 3
write(3, "nqn=nqn.2014-08.org.nvmexpress.d"..., 281) = 281
read(3, "instance=17,cntlid=4099\n", 4096) = 24
close(3)                                = 0
open("/dev/nvme17", O_RDWR)             = 3
ioctl(3, NVME_IOCTL_ADMIN_CMD, 0x7ffe3790a260) = 0
ioctl(3, NVME_IOCTL_ADMIN_CMD, 0x7ffe3790a260) = 0
ioctl(3, NVME_IOCTL_ADMIN_CMD, 0x7ffe3790a260) = 0
close(3)                                = 0
open("/sys/class/nvme/nvme17/delete_controller", O_WRONLY) = 3
write(3, "1", 1)                        = 1
close(3)                                = 0
open("/dev/nvme-fabrics", O_RDWR)       = 3
write(3, "nqn=nqn.1986-03.com.ibm:nvme:214"..., 300) = -1 EALREADY
(Operation already in progress)
```

### CODE REVIEW

**Comment by keithbusch** [comment]
You have this ending on the first record if it has an error, but don't we want to continue to the next one?

**Comment by bdeyal** [comment]
I don't know. There are some possibilities:

1. return on first error (just like my pull request)
2. best effort, try to connect as much as possible and return error code
3. Treat EALREADY differently and consider it success (possibly after reset controller)
4. All or nothing. If one fails remove the already connected ones
5. Check in advance if the connection exists (/sys/class/nvme/nvmeNN/address)

What is the correct behavior?

**Comment by keithbusch** [comment]
I think maybe print the result for each connect request individually.

**Comment by bdeyal** [comment]
OK, james smart answered in the mailing list that the behavior is intended in the case of EALREADY.

I think that this is a good solution:
Print result for each connect request (if failed)
If errno==EALREADY don't consider it as a failure, print "already connected"
For any other error exit the loop and exit code == errno.

Is it OK?

**Comment by keithbusch** [comment]
Sounds okay to me.

**Comment by bdeyal** [comment]
Updated the pull request

**Comment by keithbusch** [comment]
looks okay to me

**Pull request merged**
