### PR TITLE
Systemd ids

### PR DESCRIPTION
**Pull request by amluto**
More improvements to hostid and hostnqn.

Please review this carefully.  Also, if you merge this, please consider changing the 'luto.us' bit to something a bit more sensible.  Maybe com.github.linux-nvme?

I'm still dubious about the way that newlines in the ids are handled, but my patches don't *change* that per se.

### CODE REVIEW

**Comment by keithbusch** [comment]
Could you post this to the linux-nvme mailing list instead? I think some of the people who would have the most interest in this area don't subscribe to github.

**Comment by keithbusch** [comment]
Closing not to reject, but to direct this to linux-nvme@infradead.org because the subscribers there really should weigh in, and I can just as easily apply patches posted there when ack'ed.

**Comment by amluto** [comment]
Emailed here:

https://lore.kernel.org/linux-nvme/cover.1576726427.git.luto@kernel.org/T/#t

**Comment by amluto** [comment]
@keithbusch, this has been languishing on the list for quite a while now.  Can you take a look, please?

**Pull request closed without merging**
