### PR TITLE
nvme: add latest opcodes for command supported and effects log

### PR DESCRIPTION
**Pull request by ganaidu707**
Signed-off-by: Gollu Appalanaidu <anaidu.gollu@samsung.com>

### CODE REVIEW

**Comment by keithbusch** [comment]
Just FYI, the ZNS opcodes are specific to the ZNS command set indicator, so the opcode-to-string may not necessarily work correctly if a future command set spec re-uses the same opcodes.

**Comment by ganaidu707** [comment]
Thanks Keith, can you revert it?, I will exclude the ZNS commands specified, I thought of it and again added!

**Comment by keithbusch** [comment]
could you just sent a new patch on top of it? it's just slightly easier than to revert and rebase a new patch.

**Comment by ganaidu707** [comment]
Keith, sent a new PR, https://github.com/linux-nvme/nvme-cli/pull/887, thanks.

**Pull request merged**
