### PR TITLE
zns: Add missing Zone Attributes Information on zone descriptor

### PR DESCRIPTION
**Pull request by sc108-lee**
NVMe-Zoned-Namespace-Command-Set-Specification-1.1a-2021.07.26-Ratified
Figure 37: Zone Descriptor Data Structure - Zone Attributes Information

Signed-off-by: Steven Seungcheol Lee <sc108.lee@samsung.com>

### CODE REVIEW

**Comment by MatiasBjorling** [comment]
It'll most likely be very hard to read when multiple flags are set. Would it be worth considering to make an "extended option" - which would print out each of the separate fields in a sane format.

The same holds for the current attribute field. That is hard to read as well - but that has already been there for a long time, and may be hard to remove at this point.

**Comment by sc108-lee** [comment]
@MatiasBjorling yes I worried about same thing.
But follow the way current za print.

if change is acceptable for this,
How about this, add human readable.
with human readable : zt : string, zs : string, za : string, zai : string
without human readable : zt : hex, zs : hex, za : hex, zai : hex

**Comment by keithbusch** [comment]
Could you call the option "verbose" in order to expand the hex fields to strings?

**Comment by sc108-lee** [comment]
option name human-readable is more common in nvme-cli.
eg) nvme.c  "human-readable" : 15, "verbose" : 4
so I thought human-readable is better.
Is there any specific reason that you chose verbose??

**Comment by keithbusch** [comment]
I never liked the option name, and it doesn't fit with what it does. The default is already human readable, and the "human-readable" option just displays it more verbosely, hence i'd like to migrate to verbose options which aligns with other tools like lspci.

**Comment by sc108-lee** [comment]
@keithbusch  thanks for the explanation.

I just checked that, report_zones which call this function already has human-readable option
https://github.com/linux-nvme/nvme-cli/blob/nvme-cli-monolithic/plugins/zns/zns.c#L598

But currently there is no functionality for that.
so It might be available to be changed to verbose

**Comment by sc108-lee** [comment]
rebased after report zones json print is merged :)

**Pull request merged**
