### PR TITLE
Added abort command w/ documentation

### PR DESCRIPTION
**Pull request by bdeyal**

### CODE REVIEW

**Comment by keithbusch** [comment]
What is the justification for this? The user space doesn't know which command id's are outstanding on which submission queues, there's no way this could be used correctly or to any good outcome.

**Comment by bdeyal** [comment]
Testing.

I used admin-passthru to send the abort command (QA + testing stuff), wrapped it in a script to save some calculations, and thought maybe a built-in syntactic-sugar would be useful to others.

I agree that there's no use for this command for sysadmins and  in production environment.

**Comment by keithbusch** [comment]
Just use the admin-passthru. There is little chance such a convenience function could be used correctly in any operational environment, so I'd rather not make it "easy" to use.

**Comment by bdeyal** [comment]
ok.

**Pull request closed without merging**
