### PR TITLE
add io command set support(TP4056)

### PR DESCRIPTION
**Pull request by sc108-lee**
Signed-off-by: Steven Seungcheol Lee <sc108.lee@samsung.com>
Co-authored-by: Klaus Jensen <k.jensen@samsung.com>
Signed-off-by: Klaus Jensen <k.jensen@samsung.com>

### CODE REVIEW

**Comment by MatiasBjorling** [comment]
Please update the cover letter and commit to being descriptive of the changes you are introducing. A good introduction to commit messages are available here: https://chris.beams.io/posts/git-commit/

It is not necessary to have both a Co-authored and a signed off by for the same person. Use only one of them to show co-authorship.

**Comment by sc108-lee** [comment]
@MatiasBjorling Thanks for your advise. modified done.

**Comment by MatiasBjorling** [comment]
I do not see the commit message to be updated. There is no detailed description of what the patch intends to implement from the TP.

Also, please split the generated source code and modified source code into two patches.

**Comment by sc108-lee** [comment]
@MatiasBjorling 
Done with separation for modified and new.
Also add modification description from spec.

**Comment by keithbusch** [comment]
i appreciate the completeness of the patch set. the auto-completions do not get the attention it deserves, so thank you for taking the time to add to it.

**Pull request merged**
