### PR TITLE
nvme: fix errno for non nvme device return errors

### PR DESCRIPTION
**Pull request by ganaidu707**
Fix the shell return error numbers(errno) in overall
nvme.c file.

Signed-off-by: Gollu Appalanaidu <anaidu.gollu@samsung.com>

### CODE REVIEW

**Comment by keithbusch** [comment]
Thanks! Looks good.

**Comment by ganaidu707** [comment]
Thanks!

**Comment by ganaidu707** [comment]
Hi @keithbusch ,

Can you please have a look at the PRs: https://github.com/linux-nvme/nvme-cli/pull/1038, https://github.com/linux-nvme/nvme-cli/pull/1039, https://github.com/linux-nvme/nvme-cli/pull/1040, https://github.com/linux-nvme/nvme-cli/pull/1041, https://github.com/linux-nvme/nvme-cli/pull/1043, https://github.com/linux-nvme/nvme-cli/pull/1045, https://github.com/linux-nvme/nvme-cli/pull/1046, https://github.com/linux-nvme/nvme-cli/pull/1047, 

Thanks!

**Comment by ganaidu707** [comment]
rebased and resolved conflicts!

**Comment by ganaidu707** [comment]
@keithbusch I think this you have already been reviewed, can you have a look at this again?

Thanks!

**Comment by ganaidu707** [comment]
rebased and resolved conflicts!

**Pull request merged**
