### PR TITLE
scaleflux: support expand-cap and dump-evtlog command

### PR DESCRIPTION
**Pull request by whou-sfx**

### CODE REVIEW

**Comment by whou-sfx** [comment]
@keithbusch @igaw , please help to review the PR

**Review by igaw — CHANGES_REQUESTED** [review]
A few minor change requests:

- introduce common helper instead duplicating code
- follow coding style guidelines
- update documentation (man pages) with the new commands
- update bash/zsh tab completion (if sfx is supported)

**Comment by whou-sfx** [comment]
> A few minor change requests:
> 
> * introduce common helper instead duplicating code
> * follow coding style guidelines
> * update documentation (man pages) with the new commands
> * update bash/zsh tab completion (if sfx is supported)

thanks a lot for quickly and detail feedback, will fix them soon.

**Comment by whou-sfx** [comment]
@igaw , do you know how to doing these ? 

>update documentation (man pages) with the new commands
Add the documents about usage of scaleflux plugin command in Documentation/ directory ?  Is there any guide about how to add it?  There is no helper man pages for scalefulx commands, if you can provide a guide, we will complete them later.

>update bash/zsh tab completion (if sfx is supported)
how to achieve this ? I am not aware this before.

**Comment by whou-sfx** [comment]
@igaw , for the spinner disp util, how about this
`
 12 void spinner_disp(const char *disp_name, int progress)
 13 {
 14     static const char dash[51] = {[0 ... 49] = '=', '\0'};
 15     static const char space[51] = {[0 ... 49] = ' ', '\0'};
 16     static const char spin[] = {'-', '\\', '|', '/' };
 17     static int i = 0;
 18     /** printf("i %d, p %d, spin %d, space %d\n", i, progress, progress/2 , 50 - progress/2); */
 19     if (progress <100)
 20         printf("\r%s [%.*s%c%.*s] %3d%%", (disp_name ? disp_name : ""), progress / 2 -1, dash, spin[i % 4], 50 - progress / 2, space, progress);
 21     else
 22         printf("\r%s [%.*s] %3d%%\n", (disp_name ? disp_name : ""), 50, dash, 100);
 23     i++;
 24     fflush(stdout);
 25 }   
 26 
 27 void main(int argc, char *argv[])
 28 {
 29     int p = atoi(argv[1]);
 30     int i = 0;
 31     
 32     while (p <= 100)
 33     {
 34     
 35         spinner_disp("LogDump", p);
 36         sleep(1);
 37         
 38         i++;
 39         p+=10;
 40     }
 41     printf("\n");
 42 }  
`
And the output looks like:
`
[andy@andy-blade15 utilities]$ ./a.out 50
LogDump [========================-                         ]  50%
LogDump [=============================\                    ]  60%
LogDump [==================================|               ]  70%

LogDump [=======================================/          ]  80%
LogDump [============================================-     ]  90%
LogDump [==================================================] 100%


`

**Comment by igaw** [comment]
> @igaw , do you know how to doing these ?
> 
> > update documentation (man pages) with the new commands
> > Add the documents about usage of scaleflux plugin command in Documentation/ directory ?  Is there any guide about how to add it?  There is no helper man pages for scalefulx commands, if you can provide a guide, we will complete them later.

I just realized, for the scaleflux plugin there is no documentation at all. I would be great if you consider to provide some man patches for the scaleflux plugin. This means you just need to provide the *.txt files in https://github.com/linux-nvme/nvme-cli/tree/master/Documentation, e.g. see the various other plugins how it is done. 

> > update bash/zsh tab completion (if sfx is supported)
> > how to achieve this ? I am not aware this before.

Ah some issue here. There is no tab completion. For bash you would need to extend the bash and zsh scripts in https://github.com/linux-nvme/nvme-cli/tree/master/completions

**Comment by igaw** [comment]
> spinner_disp

Looks good, maybe just name it `util_spinner(...)` and move into the util directory. Thanks!

**Comment by whou-sfx** [comment]
> > @igaw , do you know how to doing these ?
> > > update documentation (man pages) with the new commands
> > > Add the documents about usage of scaleflux plugin command in Documentation/ directory ?  Is there any guide about how to add it?  There is no helper man pages for scalefulx commands, if you can provide a guide, we will complete them later.
> 
> I just realized, for the scaleflux plugin there is no documentation at all. I would be great if you consider to provide some man patches for the scaleflux plugin. This means you just need to provide the *.txt files in https://github.com/linux-nvme/nvme-cli/tree/master/Documentation, e.g. see the various other plugins how it is done.
> 
> > > update bash/zsh tab completion (if sfx is supported)
> > > how to achieve this ? I am not aware this before.
> 
> Ah same situation here. There is no tab completion. You would need to extend the bash and zsh scripts in https://github.com/linux-nvme/nvme-cli/tree/master/completions

ok, we will complete the document and tab completion later in another pull request.

**Comment by AndyHouHit** [comment]
@igaw , code updated based on your comments. Please help to review the changes.

**Comment by igaw** [comment]
Are you considering to update this PR?

**Comment by whou-sfx** [comment]
> Are you considering to update this PR?

The changes were merged by PR https://github.com/linux-nvme/nvme-cli/pull/1965. 
Sorry for forgetting decline the original changes.

**Comment by igaw** [comment]
All good. I was just not sure what to do with this PR. :)

**Pull request closed without merging**
