### PR TITLE
Memblaze has some feature additions and some minor changes

### PR DESCRIPTION
**Pull request by ZhangyiHuo**
1、Added clear-error-log feature
2、Support high latency log
3、Support IO latency histogram
4、Modify smart-log-add to support more projects
5、Modify some prompt words and rename some functions

### CODE REVIEW

**Comment by ZhangyiHuo** [comment]
@keithbusch Please help to review the pull request. If there is any problem, please let me know. thanks

**Comment by keithbusch** [comment]
This branch doesn't merge, could you rebase and resend the pull?

**Comment by ZhangyiHuo** [comment]
@keithbusch I have rebase and resend the pull, Please help to review the pull request.

**Comment by ZhangyiHuo** [comment]
@keithbusch If there are something wrong with the pull request, please let me konw, thank you very much.

**Pull request merged**
