### PR TITLE
nvme: use NVME_CHECK() to check get features select field value

### PR DESCRIPTION
**Pull request by ikegami-t**
Use the macro instead of comparing the long filed value definition.

### CODE REVIEW

**Comment by igaw** [comment]
```
../nvme.c:4556:13: warning: implicit declaration of function ‘NVME_CHECK’ [-Wimplicit-function-declaration]
 4556 |         if (NVME_CHECK(cfg->sel, GET_FEATURES_SEL, SUPPORTED))
      |             ^~~~~~~~~~
../nvme.c:4556:34: error: ‘GET_FEATURES_SEL’ undeclared (first use in this function)
 4556 |         if (NVME_CHECK(cfg->sel, GET_FEATURES_SEL, SUPPORTED))
      |                                  ^~~~~~~~~~~~~~~~
../nvme.c:4556:34: note: each undeclared identifier is reported only once for each function it appears in
../nvme.c:4556:52: error: ‘SUPPORTED’ undeclared (first use in this function); did you mean ‘RWF_SUPPORTED’?
 4556 |         if (NVME_CHECK(cfg->sel, GET_FEATURES_SEL, SUPPORTED))
      |                                                    ^~~~~~~~~
      |                                                    RWF_SUPPORTED
../nvme.c: In function ‘get_feature_id_print’:
../nvme.c:4595:49: error: ‘GET_FEATURES_SEL’ undeclared (first use in this function)
 4595 |                         if (NVME_CHECK(cfg.sel, GET_FEATURES_SEL, SUPPORTED))
      |                                                 ^~~~~~~~~~~~~~~~
../nvme.c:4595:67: error: ‘SUPPORTED’ undeclared (first use in this function); did you mean ‘RWF_SUPPORTED’?
 4595 |                         if (NVME_CHECK(cfg.sel, GET_FEATURES_SEL, SUPPORTED))
      |                                                                   ^~~~~~~~~
      |                                                                   RWF_SUPPORTED
```

**Comment by ikegami-t** [comment]
Rebased with the master and bumped the libnvme revision. Thank you.

**Comment by igaw** [comment]
Not totally convinced with this macro but I don't have a strong opinion. So let's go with it and see how this works out.

**Comment by ikegami-t** [comment]
Noted. Thank you.

**Pull request merged**
