### PR TITLE
nvme-cli: remove nsid parameter in error-log command

### PR DESCRIPTION
**Pull request by minwooim**
Error Information Log Page is global to controller.
So, remove unnecessary nsid parameter in nvme_error_log().

Signed-off-by: Minwoo Im <minwoo.im.dev@gmail.com>

### CODE REVIEW

**Comment by keithbusch** [comment]
I am not sure if that's true. Log pages do take namespace parameters.

**Comment by minwooim** [comment]
Keith, 
Thanks for your review.

I have reviewed NVMe 1.2.1 and 1.3 again.
SMART/Health Information log page (LID 02h) is supported on a per namespace basis.
It's shown that Error Information Log page (LID 01h) is global to the controller.

Identify Controller Data Structure contains LPA field at [261] which only cares about
extended data, command effect log page, and SMART/Health information log page.

If you don't mind, would you please let me know which case namespace is taken by device
in case of error log page?

**Comment by keithbusch** [comment]
Hm, it appears error log doesn't consult nsid.

**Comment by minwooim** [comment]
So, Are you going to keep it that way, or not?

**Comment by keithbusch** [comment]
Just need to get the Documentation/nvme-error-log.txt updated to reflect the possible parameters.

**Comment by minwooim** [comment]
Totally agree with you.
I will send a patch including that one soon.

**Pull request closed without merging**
