### PR TITLE
Fix to set correct bit  for Storage Tag Check in the IO Control Flags

### PR DESCRIPTION
**Pull request by jeffreyalien**

### CODE REVIEW

**Comment by igaw** [comment]
FYI, I just rebased it onto master and resolved the conflict in libnvme.wrap.

**Comment by jeffreyalien** [comment]
Thanks @igaw .  I didn't realize there was a conflict.  I thought this changes was pretty safe.

**Comment by jeffreyalien** [comment]
@igaw Are  you waiting on something from me for this PR?   Based on your comment above, I thought it was going to be merged into the repo, but I don't see the changes there yet.

**Comment by igaw** [comment]
All good, I just forgot to merge.

**Pull request merged**
