### PR TITLE
Add an example for attach-ns

### PR DESCRIPTION
**Pull request by rgirasegit**
Add an example to man page of attach-ns command showing syntax and information to use hexadecimal value for Namespace identifier and controller identifier.

### CODE REVIEW

**Comment by keithbusch** [comment]
The example fine, but on the explanation, the nsid and ctrl id don't need to be in hexidecimal. It will be interpreted that way if you give a 0x prefix, octal with a 0 prefix, and decimal otherwise. The ctrl id can also be a list, like '1,2,10' for a multi-ctrl subsystem.

**Comment by rgirasegit** [comment]
> The example fine, but on the explanation, the nsid and ctrl id don't need to be in hexidecimal. It will be interpreted that way if you give a 0x prefix, octal with a 0 prefix, and decimal otherwise. The ctrl id can also be a list, like '1,2,10' for a multi-ctrl subsystem.

Thank you Keith for reviewing. I have resubmitted patch. Please review it.

**Comment by keithbusch** [comment]
Eh, I should have checked first. This doesn't look like anything in the .txt was changed, and instead you've added an undesirable file to the code base. I'll fix it up.

**Comment by rgirasegit** [comment]
> Eh, I should have checked first. This doesn't look like anything in the .txt was changed, and instead you've added an undesirable file to the code base. I'll fix it up.

Keith, my bad. Should I resubmit it?

**Pull request merged**
