### PR TITLE
Add "json" option to discover command

### PR DESCRIPTION
**Pull request by martin-belanger**
The `discover` command now has a `--json` option. When the option is enabled, the output will be printed in JSON format. This makes it easier for other programs (like a Python script) to parse the output.

### CODE REVIEW

**Comment by keithbusch** [comment]
There's a json library included in the source code to handle pretty-printing these. Could you use that instead of manually formatting it?

**Comment by martin-belanger** [comment]
Ok. I will see if I can use it.

**Comment by martin-belanger** [comment]
Hi @keithbusch 
I made the changes you recommended.

**Comment by keithbusch** [comment]
Looks like Hannes sent a pull request for the same feature, https://github.com/linux-nvme/nvme-cli/pull/937/commits/d22d5bdd9288fac06ee6fca9dec5654b5bd466ff. I'll pull that one since it is a bit more complete with the manpage updates and other minor details.

**Pull request closed without merging**
