### PR TITLE
nvme: Change to use pci resource bar at first by show-regs command

### PR DESCRIPTION
**Pull request by ikegami-t**
This is to prevent the nvme error log mentioned by the issue #1593.

Signed-off-by: Tokunori Ikegami <ikegami.t@gmail.com>

### CODE REVIEW

**Comment by igaw** [comment]
It is a kernel bug which has been addressed by https://git.infradead.org/nvme.git/commitdiff/ecaec17576195ad45022d41a7092d895acdf1d0c

This fix should be back ported to all affected LTS kernels.

There are a few more places where nvme-cli/libnvme would trigger to verbose logging. So I don't think it helps just to patch up one place. IIRC, these register are also not available when `CONFIG_IO_STRICT_DEVMEM` is set.

**Comment by ikegami-t** [comment]
Seems as basically the unnecessary or unsupported commands should not be submitted to device. But is it really not necessary to fix for the prevention?

**Comment by igaw** [comment]
We can't really know upfront which command will fail. Thus libnvme is probing if a feature is supported before using it. IIRC we do the same thing in the kernel driver.

**Comment by igaw** [comment]
Sure, if we can reliable detect the `CONFIG_IO_STRICT_DEVMEM` config option.

**Comment by ikegami-t** [comment]
Thanks for your comments. I will do consider more for your advices.

**Comment by igaw** [comment]
> Sure, if we can reliable detect the `CONFIG_IO_STRICT_DEVMEM` config option.

I think you could just try to mmap the regs and when this fails use fabrics approach. Though how should we handle the error message. Currently we will print `Did your kernel enable CONFIG_IO_STRICT_DEVMEM`. Should we just turn it into a debug message which will only be visible with the `--verbose` command line option?

**Comment by igaw** [comment]
Ah that is actually what your patch does. Right, so please turn the error message into a debug message and I think you should add the error message when both approaches fail or are we printing anything useful when the fabrics approach fails?

**Comment by ikegami-t** [comment]
Thanks for your understanding. Just fixed for your comments so please review again.

**Comment by igaw** [comment]
Thanks! I've applied the patch directly after making the error message on `CONFIG_IO_STRICT_DEVMEM` conditional on the debug flag.

**Pull request closed without merging**
