### PR TITLE
[nvme-cli] Improve formatting for vs-smart-add-log output

### PR DESCRIPTION
**Pull request by jeffreyalien**
Signed-off-by: Jeff Lien <jeff.lien@wdc.com>

### CODE REVIEW

**Comment by igaw** [comment]
Can you also send a PR for master, please?

**Comment by igaw** [comment]
BTW, I am not completely sold on adding non bug fixes to the monolithic branch at this point.

**Comment by jeffreyalien** [comment]
Ok, I can do that.  I wasn't sure of the policy for changes in the monolithic branch.  In the future I'll only make bug fixes there and everything else with go into the master.

**Comment by igaw** [comment]
Yeah, I think we should not try to add anything to the monolithic branch which is not a clear bug fix in the near future. The aim is to get libnvme 1.0 nvme-cli 2.0 out the door. After we fixed the to be expected fallouts I think we can stop maintaining the v1.x (monolitith) branch.

**Comment by jeffreyalien** [comment]
@igaw Created pull request #1250 for the master branch.   Let me know if you want me to close this PR.

**Comment by igaw** [comment]
Merge the PR for master. Let's close this one. Thanks!

**Pull request closed without merging**
