### PR TITLE
nvme: update to nvme_scan_filter_t modifications

### PR DESCRIPTION
**Pull request by igaw**
nvme: update to nvme_scan_filter_t modifications

The scan filter in libnvme has been updated, so update the code
to make use of it.

Signed-off-by: Hannes Reinecke <hare@suse.de>
[dwagner: show also paths for discvoery controller]
Signed-off-by: Daniel Wagner <dwagner@suse.de>

Replaces #1482 and #1481

### CODE REVIEW

**Comment by igaw** [comment]
One thing which I find a bit irritating that is the fact we hide this feature how to show the ANA state. It's not documented. Why don't we just show it always. And the next thing is why don't we have a proper command line options e.g. '-d/--device' as we have other commands?

**Comment by igaw** [comment]
Hmm, still a regression in this version

```
nvme-subsys0 - NQN=nqn.2017-03.jp.co.toshiba:KXG60ZNV512G NVMe TOSHIBA 512GB:49MA23BZK03N
\
carbon:/home/wagi/work/nvme-cli # nvme list-subsys
nvme-subsys0 - NQN=nqn.2017-03.jp.co.toshiba:KXG60ZNV512G NVMe TOSHIBA 512GB:49MA23BZK03N
\
 +- nvme0 pcie 0000:3d:00.0 live 
```

**Comment by igaw** [comment]
For multipath setups:

```
 # .build/nvme list-subsys
nvme-subsys1 - NQN=nqn.2014-08.org.nvmexpress:NVMf:uuid:de63429f-50a4-4e03-ade6-0be27b75be77
\
 +- nvme1c1n1 tcp traddr=10.161.8.24,trsvcid=4420 live optimized
 +- nvme1c3n1 tcp traddr=10.161.8.24,trsvcid=4421 live optimized
nvme-subsys0 - NQN=nqn.2014-08.org.nvmexpress.discovery
\
 +- nvme0 tcp traddr=10.161.8.24,trsvcid=4420 live
```

@hreinecke I suppose we want to show 'nvme1 ....' and 'nvme3 ....' instead of 'nvme1c1n1'?

and for PCI transport:

```
# .build/nvme list-subsys 
nvme-subsys0 - NQN=nqn.2017-03.jp.co.toshiba:KXG60ZNV512G NVMe TOSHIBA 512GB:49MA23BZK03N
\
 +- nvme0 pcie 0000:3d:00.0 live

```

**Comment by hreinecke** [comment]
How would you print the ANA state if you don't have a namespace specified?

**Comment by hreinecke** [comment]
Far better.

**Pull request merged**
