### PR TITLE
plugin/ocp: Added implementation for Error Recovery(0xC1) log page

### PR DESCRIPTION
**Pull request by jayakanthan-94**
plugin/ocp: Added implementation for 0xC1 log page

Reviewed-by: Karthik Balan <karthik.b82@samsung.com>, Arunpandian J <arun.j@samsung.com>
Signed-off-by: Jayakanthan Rajendran [jaya.ganthan@samsung.com](mailto:jaya.ganthan@samsung.com)

### CODE REVIEW

**Comment by igaw** [comment]
@arthurshau

**Comment by jayakanthan-94** [comment]
@igaw 
build / cross armhf build has got failed. Looks like it got failed due to network issue while trying to download some packages. Please check

**Comment by arthurshau** [comment]
Logic looks good to me. But re: formatting, overall, I'd like to keep the functions for each of the commands in their own sections. So that would mean moving all of the functions and structs for Log Page C1 into a block defined by a comment like this: 
```
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
/// Error Recovery Log
```
Alternatively, you can also move it all to the "Misc" section at the end too if you want.

@igaw can chime in here, since we've talked about this before. But I think it's a better to have these comment blocks right now, than to have all the structs and functions interspersed randomly throughout the file, at least.

**Comment by igaw** [comment]
> @igaw can chime in here, since we've talked about this before. But I think it's a better to have these comment blocks right now, than to have all the structs and functions interspersed randomly throughout the file, at least.

Makes sense to group them inside the file. If they are getting to big, we can still move them into separate files.

**Comment by jayakanthan-94** [comment]
> Logic looks good to me. But re: formatting, overall, I'd like to keep the functions for each of the commands in their own sections. So that would mean moving all of the functions and structs for Log Page C1 into a block defined by a comment like this:
> 
> ```
> ///////////////////////////////////////////////////////////////////////////////
> ///////////////////////////////////////////////////////////////////////////////
> ///////////////////////////////////////////////////////////////////////////////
> ///////////////////////////////////////////////////////////////////////////////
> /// Error Recovery Log
> ```
> 
> Alternatively, you can also move it all to the "Misc" section at the end too if you want.
> 
> @igaw can chime in here, since we've talked about this before. But I think it's a better to have these comment blocks right now, than to have all the structs and functions interspersed randomly throughout the file, at least.

@arthurshau  @igaw Moved it to separate block. Please check.

**Comment by arthurshau** [comment]
LGTM

**Comment by igaw** [comment]
I've squashed the commits but it seems they don't merge. Could you please update the merge? Thanks.

**Comment by jayakanthan-94** [comment]
> I've squashed the commits but it seems they don't merge. Could you please update the merge? Thanks.

Hi @igaw ,

I have resolved merge conflicts and squashed all commits. Please check.

**Comment by igaw** [comment]
Fixed the commit message I screwed up. 

Anyway, can you also send a PR which updates the bash and zsh shell completions. See @ikegami-t recent fixes: https://github.com/linux-nvme/nvme-cli/commit/8fa0d817af2ca4ba49d4535c16950b21ccf0e683

**Comment by jayakanthan-94** [comment]
> Fixed the commit message I screwed up.
> 
> Anyway, can you also send a PR which updates the bash and zsh shell completions. See @ikegami-t recent fixes: [8fa0d81](https://github.com/linux-nvme/nvme-cli/commit/8fa0d817af2ca4ba49d4535c16950b21ccf0e683)

Sure @igaw . I will push it as part of next PR.

**Pull request merged**
