### PR TITLE
Zns completions

### PR DESCRIPTION
**Pull request by sc108-lee**
zsh (subcommand level support)
bash (Add subcommand and options level support, Add plugin feature with function)
modify report zone option

### CODE REVIEW

**Comment by sc108-lee** [comment]
@keithbusch 
Do you prefer using plugin function inside of case instead of using checking function existence logic??

**Comment by shmily1012** [comment]
Hi There,

I am wondering if you have plan to include the 'ZRWA' related feature in TP4076.

Thanks,
Alex

**Comment by MatiasBjorling** [comment]
Hi @shmily1012 

The ZRWA technical proposal is in the progress of being standardized within the NVMe ZNS Task Group.  Support will be added when the TP has been ratified and integrated into the ZNS Command Set specification. 

Best, Matias

**Comment by sc108-lee** [comment]
Hi @shmily1012 
As Matias mentioned, TP is under progress.
once TP is ratified, I might be able to do that feature.
Thanks

**Comment by shmily1012** [comment]
Hi @sc108-lee  and @MatiasBjorling,
Sounds good. Thanks for the quick response. 
Regards,
Alex

**Comment by sc108-lee** [comment]
@keithbusch if you have any other reason to not using this, let me know :)
it could be issued as "plugin_list_opts_zns ${words[2]} $prev" under the case.
but I add like this to skip cases for the plugins

**Comment by sc108-lee** [comment]
since there is other PR has been accepted, this PR means nothing.
so close it.

**Pull request closed without merging**
