### PR TITLE
zns: small cleanups to zrwa

### PR DESCRIPTION
**Pull request by MatiasBjorling**
A couple of cleanups for the ZRWA to align it with the existing
style.

Signed-off-by: Matias Bjørling <matias.bjorling@wdc.com>

### CODE REVIEW

**Comment by igaw** [comment]
I've fixed some coding style issues and updated the documentation. Can you check if all still okay? If so I'll merge those two commit together before applying them.

**Comment by MatiasBjorling** [comment]
Looks good. Thanks! 

Gotta fix my vim - I've got the view of tabs and spaces view disabled.

**Comment by sc108-lee** [comment]
I can agree for changes, I hope those comment are enough answer for your last questions

**Comment by MatiasBjorling** [comment]
Thanks. Yep, all good with me.

**Pull request merged**
