### PR TITLE
ocp: add get-enable-ieee1667-silo command

### PR DESCRIPTION
**Pull request by ikegami-t**
The commands returns set of enable IEEE1667 silo.

### CODE REVIEW

**Comment by igaw** [comment]
@arthurshau and one more to review!

**Comment by ikegami-t** [comment]
Fixed the issue title and commit message errors.
```diff
- opc: add get-enable-ieee1667-silo command
+ ocp: add get-enable-ieee1667-silo command
```
Note: Still will be added set-enable-ieee1667-silo command, documentations and completions later by separated patches.

**Comment by arthurshau** [comment]
LGTM!

**Comment by igaw** [comment]
Thanks!

**Pull request merged**
