### PR TITLE
Add zone-mgmt-recv parameters to issue command

### PR DESCRIPTION
**Pull request by sc108-lee**

### CODE REVIEW

**Comment by keithbusch** [comment]
On second thought, why call this "partial" for the generic zone-mgmt-recv? That parameter is defined to "partial" only for specific receive actions.

**Comment by sc108-lee** [comment]
@keithbusch 
original value name was (zrass)
zrass was not clear because the 16th bit is Zone Receive Action Specific Features.
And zrasf is taken by Zone Receive Action Specific Field.
so I just use that partial.
should we change this to other name?

**Comment by keithbusch** [comment]
I would like to change it because this is the generic command interface and 'partial' is the name of the field when it is specific to specific actions. The generic name, "Zone Receive Action Specific Features" unfortunately shares the same acronym as another field, "Zone Receive Action Specific Field".

**Comment by sc108-lee** [comment]
zras-feat, zras-field
how does it sound?

**Pull request merged**
