### PR TITLE
Add Inspur plugin extension.

### PR DESCRIPTION
**Pull request by wangmengmeng02**
Add sub-command to retrieve Inspur device Vendor log.

### CODE REVIEW

**Comment by wangmengmeng02** [comment]
Add sub-command to retrieve Inspur device Vendor log.

Signed-off-by: wangmengmeng [wangmengmeng02@inspur.com]

**Review by igaw — CHANGES_REQUESTED** [review]
A couple of small things:

- Could you drop the `.1` and `.html` documentation files. These will be auto generated for the next release. 
- The documentation for the data structs seems to be javadoc(?) but we are using kernel-doc comments. I also suggest not to mentioning the byte address in the comment as these get easy out of sync. It's better to us pahole to verify the position and alignment of the members.

Rest looks good.

**Comment by wangmengmeng02** [comment]
> * Could you drop the `.1` and `.html` documentation files. These will be auto generated for the next release.

@igaw ,thanks for reviewing, this comment means drop all the modification in directory Documentation/* or only *.1 and *.html document?

**Comment by igaw** [comment]
> @igaw ,thanks for reviewing, this comment means drop all the modification in directory Documentation/* or only *.1 and *.html document?

No just do not add the generated documents. In our case these are the *.1 and *html files. The *.txt file should stay as it is the source for the other files.

**Comment by wangmengmeng02** [comment]
update for comments

**Review by igaw — APPROVED** [review]

**Comment by igaw** [comment]
I've merged the PR directly after small changes:
- updated the commit message slightly
- added a bunch of newlines
- switch iterator types to `int`

**Pull request closed without merging**
