### PR TITLE
ymtc: fix ymtc additional smart info display

### PR DESCRIPTION
**Pull request by Ssd5513146**
fix ymtc additional smart info display

### CODE REVIEW

**Comment by Ssd5513146** [comment]
done.thanks

**Comment by Ssd5513146** [comment]
done

**Comment by igaw** [comment]
Could you prefix the commit subject with ymtc? E.g.

`ymtc: fix additional smart info display`

Thanks

**Comment by igaw** [comment]
I was talking about the commit message not the github PR title.

```shell
git commit --edit --amend
[change subject title]
git push -f
```

I would have done this myself but the PR is not based from a branch, hence I can push the change on your branch and merge it from there. Well, that's not your fault, it's just how github works...

**Pull request merged**
