### PR TITLE
plugins/wdc: Add support for SN660 drive

### PR DESCRIPTION
**Pull request by jeffreyalien**
Update WDC plugin version to 2.1.2

Signed-off-by: Jeff Lien <jeff.lien@wdc.com>

### CODE REVIEW

**Comment by jeffreyalien** [comment]
@igaw Updated title.

**Comment by igaw** [comment]
I was referring to the commit not the github title :)

**Comment by jeffreyalien** [comment]
@igaw Done, sorry for the mix up.

**Comment by igaw** [comment]
No worries, all good.

**Pull request merged**
