### PR TITLE
Tp4115

### PR DESCRIPTION
**Pull request by sc108-lee**
this PR based on https://github.com/linux-nvme/nvme-cli/pull/1833

### CODE REVIEW

**Comment by sc108-lee** [comment]
this PR based on #1833

**Comment by igaw** [comment]
Please update the libnvme.wrap first (note it has a new sha ref).

**Comment by sc108-lee** [comment]
@igaw after merge https://github.com/linux-nvme/nvme-cli/pull/1894 this commit will update hash :)

**Comment by igaw** [comment]
Can you update the PR? I've just merged the libnvme bits.

**Comment by igaw** [comment]
Updated the ref in the libnvme wrap file. The current nvme-cli HEAD wont compile against libnvme HEAD.

**Comment by sc108-lee** [comment]
@igaw Thanks for the update :) will close #1833

**Pull request merged**
