### PR TITLE
Trying to get a ppc64le build going

### PR DESCRIPTION
**Pull request by ericcurtin**
Fix warnings along with that

### CODE REVIEW

**Comment by ericcurtin** [comment]
There's demand from a couple of places:

https://bugzilla.redhat.com/show_bug.cgi?id=1854495
#772
#784

**Comment by ericcurtin** [comment]
This compiles but doesn't link, we need the ppc64el version of libuuid to link. Not 100% sure if ubuntu has a mirror for that. We could add a compile-only option to the makefile for ppc64el variant or do this properly and get libuuid ppc64el variant installed on CI server.

**Comment by ericcurtin** [comment]
Removed libuuid dependency, we can cross-compile for ppc64le no problem now!

**Comment by ericcurtin** [comment]
It solves a problem also, for example, ubuntu 20.04, don't build with libuuid and just sacrafice functionailty:

```
$ nvme gen-hostnqn
"gen-hostnqn" not supported. Install lib uuid and rebuild.
```

now for downstream packages this will always work as libuuid is now not required to generate a random uuid, theres a feature in the Linux kernel for that.

```
$ nvme gen-hostnqn
nqn.2014-08.org.nvmexpress:uuid:4df83088-40cf-434a-8b09-23ab9a2f9514
```

**Comment by keithbusch** [comment]
If we can use libuuid, then let's use it. If you want to re-implement it for when it's not available, then fine, but let's not compile in the reinvention if we don't need to. It actually sounds odd that libuuid is not available on ppc, though. Is there a technical reason for that?

**Comment by ericcurtin** [comment]
You are right LD=powerpc64le-linux-gnu-ld is all I needed.

Will push this and re-implement uuid generator from /proc file in another PR

**Comment by ericcurtin** [comment]
Mind looking at this again @keithbusch ?

**Pull request merged**
