### PR TITLE
doc: show where self-test results can be found

### PR DESCRIPTION
**Pull request by paumr**
As a first-time user I was wondering on where to find the `device-self-test` results.

I think adding this information to the `device-self-test` documentation would be quite useful.

### CODE REVIEW

**Comment by igaw** [comment]
Looks good. 

Just a nit: Could you add your Signed-off-by to the commit message? Or I can add it if it's okay for you.

Thanks!

**Comment by paumr** [comment]
Thanks! Sure, I signed the commit - thanks for the review.

**Comment by igaw** [comment]
We follow the Linux kernel mailing list workflow, thus commit message itself should be something like

```
doc: show where self-test results can be found

Point out where find results when running the self tests.

Signed-off-by: My Name/alias <email.address.foo>
```

**Comment by paumr** [comment]
Done, sorry for the delay, I did not receive a notification about your most recent message.

**Comment by igaw** [comment]
Thanks!

**Pull request merged**
