### PR TITLE
Add support for codeql sweeps

### PR DESCRIPTION
**Pull request by AM-K-19**
Add codeql.yml configuration file to allow routine static and vulnerability checks. By the way, codeql has detected one issue on the current head of master. I can provide additional details if required.

### CODE REVIEW

**Comment by igaw** [comment]
Thanks! Let's see how this goes.

**Comment by igaw** [comment]
I see a warning reported:

```
Could not process some files due to syntax errors
[View file](https://github.com/linux-nvme/nvme-cli/blob/master//home/runner/work/nvme-cli/nvme-cli/subprojects/libnvme/libnvme/__init__.py#L1-L1)

A parse error occurred while processing /home/runner/work/nvme-cli/nvme-cli/subprojects/libnvme/libnvme/\_\_init\_\_.py, and as a result this file could not be analyzed. Check the syntax of the file using the python -m py\_compile command and correct any invalid syntax.
```

**Comment by igaw** [comment]
We should probably exclude the subprojects from the scan.

**Comment by AM-K-19** [comment]
> We should probably exclude the subprojects from the scan.

Yes, that sounds sensible. Leave it with me. I'll try to figure out how to exclude such directories from the scan.

**Comment by AM-K-19** [comment]
I've created this new pull request:
https://github.com/linux-nvme/nvme-cli/pull/2115

**Pull request merged**
