### PR TITLE
Add Virtium plugin extensions

### PR DESCRIPTION
**Pull request by quyentruongvir**
Add Virtium plugin extensions, please help me reviewing.

### CODE REVIEW

**Comment by keithbusch** [comment]
Could you please also add a man page for this in the Documentation/ directory?

**Comment by Pho-Virtium** [comment]
Hello Keith,

What is the best way to create those files in the Documentation directory? 

Thank you & regards,

Pho Hoang
Virtium LLC

**Comment by keithbusch** [comment]
Add .txt files in Documentation/ named like "nvme-virtium-<command>". It looks like you are adding two vendor specific commands so, you'll add two .txt files named for each command. The format of the contents is asciidoc, and there are lots of existing .txt files if you need a reference on how to format your manual.

**Comment by Pho-Virtium** [comment]
Thank you so much, Keith!

**Pull request merged**
