### PR TITLE
Change command name

### PR DESCRIPTION
**Pull request by Dequan-Dera**
Change command 'stat' to 'smart-log-add' and its description

### CODE REVIEW

**Comment by keithbusch** [comment]
This is highly unusual. For the sake of backward compatibility, you should make the "old" name of this command an alias to the new name. Sound okay?

**Comment by Dequan-Dera** [comment]
Add new command named 'smart-log-add', make old 'stat' an alias to the new name.

**Comment by keithbusch** [comment]
Sorry, I should have been more clear. On the "ENTRY" line, there is an optional 4th argument for alias names. This way it doesn't show up in the "help" so it discourages new use on the now deprecated name, but it allows existing scripts to run uninterrupted.  The end result should look something like this:

`ENTRY("smart-log-add", "Retrieve Dera SMART Log, show it", get_status, "stat")`

**Comment by Dequan-Dera** [comment]
Add new command named 'smart-log-add', make old 'stat' an alias to the new name. Sorry for ignorance of great character of ENTRY. Thank you.

**Comment by keithbusch** [comment]
squashed and committed via command line

**Pull request closed without merging**
