### PR TITLE
For upstream/tp4095

### PR DESCRIPTION
**Pull request by sc108-lee**
Based on libnvme PR https://github.com/linux-nvme/libnvme/pull/166

I was add these command into original id-ns, zns id-ns ...
But this command does not need NSID.

So I split this command as a new command.
if have any opinion for this, please let me know :)

### CODE REVIEW

**Comment by igaw** [comment]
I think the CI build is able to build against the matching libnvme commit. You just need to specify the matching ref in subprojects/libnvme.wrap.

**Comment by igaw** [comment]
@MatiasBjorling you want probably to review this first :)

**Comment by sc108-lee** [comment]
rebased :)

**Comment by sc108-lee** [comment]
rebased and added one commit
https://github.com/linux-nvme/nvme-cli/pull/1312/commits/30703696f0440ab146503d98c2010ac964053bfb

**Comment by igaw** [comment]
Just reordered the commits.

**Pull request merged**
