### PR TITLE
Update nvme.c

### PR DESCRIPTION
**Pull request by jinhua2021**
$date +"%s%3N" >timestamp.log
$cat timestamp.log
1627131384309

$./nvme set-feature /dev/nvme0 -f 0x0e -v 1627131384309 
it works well, because it reads the value correctly.

$./nvme set-feature /dev/nvme0 -f 0x0e -d timestamp.log
It will read the timestamp file as data len 8, but actual it is 13. It only memcpy 16271313 instead of 1627131384309.

It will make set-feature, get-feature wrong behave for timestamp.

### CODE REVIEW

**Comment by franciscomunoz** [comment]
@jinhua2021 I would like to add that I've been testing activation history and FID 0x0e is working as is.

**Comment by jinhua2021** [comment]
@franciscomunoz @keithbusch
Thanks for your reply.

I would like to make it clear as follow:

**Comment by jinhua2021** [comment]
I updated the PR and the description.

**Comment by keithbusch** [comment]
Are you trying to write a string into this value instead of the integer representation?

**Comment by keithbusch** [comment]
eh, this particular feature is implemented so badly...

Your patch won't work because the read size exceeds the buffer size.

I'll fix this up.

**Comment by keithbusch** [comment]
I'm just going to remove the string conversion for now since trying to support it is a mess at the moment. Just use the integer representation.

Also, this is not something a user should be setting anyway. The driver sets this during device probe, and overriding it can cause some unusual issues on the device side.

**Pull request closed without merging**
