### PR TITLE
plugins/solidigm: Added workload-tracker command

### PR DESCRIPTION
**Pull request by lgdacunh**
Added set up and continuous parse and consolidation of workload log.

### CODE REVIEW

**Comment by lgdacunh** [comment]
@igaw, checkpatch is throwing an error when you add a new file. I think the new file makes sense in this case.

**Comment by igaw** [comment]
> @igaw, checkpatch is throwing an error when you add a new file. I think the new files make sense in this case.

checkpatch is wrong in our case. We don't have a maintainer file, so it doesn't really make sense. Hmm we could though add one, but I don't know if this make sense or it is generally something the plugins maintainers are interested in.

**Comment by igaw** [comment]
I've merge the update directly after resolving the merge conflict.

**Comment by lgdacunh** [comment]
> I've merge the update directly after resolving the merge conflict.

Thanks!

**Comment by lgdacunh** [comment]
> > @igaw, checkpatch is throwing an error when you add a new file. I think the new files make sense in this case.
> 
> checkpatch is wrong in our case. We don't have a maintainer file, so it doesn't really make sense. Hmm we could though add one, but I don't know if this make sense or it is generally something the plugins maintainers are interested in.
I am not aware of how the maintainer file works, but I would be interested if it streamline the automated checks.

**Pull request closed without merging**
