### PR TITLE
Ocp hwcomp

### PR DESCRIPTION
**Pull request by ikegami-t**

### CODE REVIEW

**Comment by ikegami-t** [comment]
The first commit is based with the PR #2485 and next three commits cherry picked from the PR #2486, #2487 and #2488.

**Comment by igaw** [comment]
@arthurshau could also look at this one? Thanks!

**Comment by ikegami-t** [comment]
Just rebased with the master merged the three PRs depended.

**Comment by ikegami-t** [comment]
Rebased with the PR #2487 changes.

**Comment by arthurshau** [comment]
LGTM

**Comment by ikegami-t** [comment]
Rebased with the latest PR #2487 changes.

**Comment by igaw** [comment]
I've tried to rebase it to the latest upstream version but there were non trivial merge conflicts. Could you rebase this branch again? Thanks!

**Comment by ikegami-t** [comment]
Just rebased the changes. Thank you.

**Comment by igaw** [comment]
Thanks!

**Pull request merged**
