### PR TITLE
Tp4146

### PR DESCRIPTION
**Pull request by sc108-lee**

### CODE REVIEW

**Comment by sc108-lee** [comment]
it looks muon does not recognize commit on PR
https://github.com/linux-nvme/libnvme/pull/582/commits/c32d360954bd655f2de19c8a08297b41ac56ce3c

**Comment by sc108-lee** [comment]
This commit will be modified after libnvme TP4146 merged

**Comment by igaw** [comment]
> it looks muon does not recognize commit on PR [linux-nvme/libnvme@c32d360](https://github.com/linux-nvme/libnvme/commit/c32d360954bd655f2de19c8a08297b41ac56ce3c)

The muon build is trying to fetch it from the orig repo and I think anything which is just a PR wont be fetched correctly. The CI instruction are a bit too simple. On the other hand, it will prevent to merge something which isn't in libnvme. So it's a feature :)

**Comment by igaw** [comment]
I've merged PR #1894. It looks like this one doesn't have new changes ontop of #1894.

**Pull request closed without merging**
