### PR TITLE
Implementation for SED/Opal 

### PR DESCRIPTION
**Pull request by ScottyBauer**
Don't worry about pulling/reviewing this yet, Keith. Just getting everything staged.

This will change a few times as upstream potentially has us modify API. Once sed has landed then we can review this.

### CODE REVIEW

**Comment by cristim** [comment]
I think this can be reopen now, the sed patches landed a couple of months ago.

**Comment by whirm** [comment]
Any plans on getting this functionality merged?

**Comment by ScottyBauer** [comment]
No. Sed-opal is storage agnostic and doesn't belong in nvme-cli. https://github.com/Drive-Trust-Alliance/sedutil/issues/90  is in the midst of incorporating OPAL_SAVE into their tooling, https://github.com/ScottyBauer/sed-opal-temp/ is another set of tooling you can use as well.

**Comment by whirm** [comment]
@ScottyBauer great thanks! Is sed-opal-temp functional? Does it support suspension?

**Comment by ScottyBauer** [comment]
@whirm Yes, it will allow you to set a key in the kernel so you can unlock from S3. There are some examples in scripts/ on how to setup your drive, if it's not already opal-enabled. If you setup your drive via DTA sed-util you'll have to send the _hashed_ password via the sed-util tooling.

**Comment by whirm** [comment]
@ScottyBauer I'll have a look ASAP. Thanks again!

**Pull request closed without merging**
