### PR TITLE
Nvme 2.0 Changes

### PR DESCRIPTION
**Pull request by jeffreyalien**
Added get_mi_cmd_support_effects_log and help text
Print out new persistent_event_log fields - ehai and pelpid
Added function to print the ID NS NSATTR field in human readable text
Dependent on libnvme commit 3dc85542e84c6ffaff86bea4ca754ccbf75bf89c.  I updated subprojects/libnvme.wrap.  Not sure if there on any other requirements for dependent changes.

### CODE REVIEW

**Comment by igaw** [comment]
Please rewrite your commit subject and message. I've done this for you in the last PR, so you can check what style it should be.

**Comment by jeffreyalien** [comment]
@igaw I'm not sure what you're looking for.  Are you referencing PR 306 as an example of what you want?  If so, I still don't see what you're asking for.  I don't have a problem updating the subject and messages but just want to understand what you're looking for.  Let me know, thanks.

**Comment by jeffreyalien** [comment]
@igaw I updated the commit subject messages.  Let me know if that's what you're looking for.  Thanks

**Comment by igaw** [comment]
- Rebased on the current master
- dropped all the libnvme.wrap patches. already up to date
- Shortened the subject title even more
- Reformated documentation file (80 chars)

Sorry for the delay. Anyway, the commit message are way better. The aim is to follow more closely to the commit message style as we have in the Linux kernel tree. Thanks.

**Comment by jeffreyalien** [comment]
@igaw I see you removed the .1 and .html doc files from the PR and then regenerated them.   So going forward, I assume you'll want just the .txt file included in the PR?  And then you'll do a doc regen after it's been accepted?

**Comment by igaw** [comment]
Yes, that would be great. it's simpler to review just the pure source files. The plan is to regenerate the docs before a release. This makes sure everything stays consistent. Furthermore, the date in the man pages are synced up too.

**Pull request merged**
