### PR TITLE
Implement json output for list that matches 'isdtc show -output json --intelssd

### PR DESCRIPTION
**Pull request by ScottyBauer**
…--intelssd'

    New command:
    nvme list -json -intelssd or
    nvme list -json  or
    nvme list

Signed-off-by: Scott Bauer <scott.bauer@intel.com>

### CODE REVIEW

**Comment by ScottyBauer** [comment]
The only difference between this and isdct is we won't report  "Bootloader is up-to-date ..." That seems strange to be looking for that in this tool. If we really need it I can go ahead and put it in.

**Comment by ScottyBauer** [comment]
I'll have to re-word the commit it should be -intel not -intelssd.

Anyway, another thing to ponder before merging is do we want to keep -json or use the -output-format JSON that the rest of the code base uses?

**Comment by keithbusch** [comment]
Don't worry about the bootloader up-to-date part. That only works if the firmware and bootloader are built into the program, which is not the case for the open tooling. We are good to just display what the device returns.

Let's also remove the "intel" specific list option. If we need an intel specific one, we'll put it in the intel vendor plugin.

As for reporting models would it be feasible to pull these out of the pci.ids file? This is how 'lspci' does it, and would be convenient to use so we don't need to update multiple repositories with model name decoding. It may be a bit more work, though, since it isn't straight forward to get the SVID:SSID from a block handle.

**Comment by jderrick** [comment]
Those should be in /sys/class/nvme/nvme0/device/subsystem_{device,vendor}

**Comment by ScottyBauer** [comment]
Thanks Jon, that helped a bunch.

Keith, with the removal of the intel flag, can we rely on the bootloader and the health status being in the same location for devices manufactured by other companies? I'm essentially asking if I need to remove that whole chunk of code and place it in the vendor plugin?

**Comment by keithbusch** [comment]
The health and bootloader are vendor specific and don't need to be reported in the generic version of this command.

**Comment by ScottyBauer** [comment]
Changes from V1->V2:

Added Function to pull out controller names via /usr/share/hwdata/pci.ids

output looks like:
{
  "PCIe Nvme  DC P3700 SSD CVFT516500..etc":
        etc
}

It does not include the Manufacturer ie, Intel, Samsung, etc. We *can* get that info from pci.ids, but it adds a little more complexity to the parsing code due to re-use of manufacture numbers within the file.

**Comment by ScottyBauer** [comment]
I'd like to get this branch in a solid state, I have a bunch of other work that is branched on top of this one. Once this is stable I can rebase all that other work and get it here for review.

**Comment by ScottyBauer** [comment]
v2->v3 
Rebased ontop of Christoph's changes. Changed  from -json to the more standard -output-format json|normal that is used throughout the file.

**Comment by keithbusch** [comment]
This feature was pulled in a different request; closing.

**Pull request closed without merging**
